apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cachet.fullname" . }}
  labels:
{{ include "cachet.labels" . | indent 4 }}
stringData:
  DB_PASSWORD: {{ .Values.database.password | quote }}
{{- range $key, $value := .Values.env.private }}
  {{- if $value  }}
  {{ $key }}: {{ $value | quote}}
  {{- end }}
{{- end -}}
